repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.8.9 # uv version
  hooks:
    - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.0 # ruff version
  hooks:
    - id: ruff-check
    - id: ruff-format